### ISSUE TITLE
Color Command

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#11]
Details have not yet been decided (need a way to set the current users color role, add predefined colors, and remove unused color roles).

**Comment by cloewen8** [comment]
This was basically already done by gt_c. Some modifications will need to be made to handle externally stored color roles (definitions from the database).

**Comment by cloewen8** [comment]
Just needs a `color` alias and settings.

**Comment by gt-c** [comment]
Completed.
