### ISSUE TITLE
Roblox Muting

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#19]
A set of commands to *mute* and *unmute* a Roblox user by their user id. The command would check for their user id in the message's username. If a muted user's message is posted, it should be removed as quickly as possible.

**Comment by cloewen8** [comment]
Required for the new Roblox Suggestions module.

**Comment by gt-c** [comment]
This doesn’t seem to meet Bro Bot’s purpose currently. Therefore I am closing this issue. Reopen if you disagree with me.
