### ISSUE TITLE
Game Engine

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#228]
Game javascript files will be in a games folder in `cloewen8/Bro-Time-Server/server/`. 
The game command will be in the `cloewen8/Bro-Time-Server/server/server/commands` folder.
Upon triggering of the command (`!game`) the command will check if the first paramater specified is the name of a js file in the games folder. Example: tictactoe, number. If it isn't, it will return a list of game options to play. If the first parameter is not specified, it will return a list of game options to play and the usage of the command. The game javascript fles will probably need to be in some form of module that supplies the call variable.

**Comment by cloewen8** [comment]
For security, the modules should be preloaded and validated.

**Comment by cloewen8** [comment]
What is the *number* game?

**Comment by cloewen8** [comment]
How would this work as a possible module design? [Lucidchart Document](https://www.lucidchart.com/invitations/accept/9477d5a8-1f8f-4dfd-b674-4623474be129)

**Comment by gt-c** [comment]
the number game would be a game where you guess a number between _x_ and _x_ and you have like 5 tries or something

**Comment by cloewen8** [comment]
For consistency with the commands core, I will include the *id* and *test* properties. At this point, developers can begin to design games using this feature.

**Comment by cloewen8** [comment]
I planned out the game engine. I used standard symbols with swim lanes. I also used circles to denote parts that processes can be introduced for multi-threading in the future. Promises will be used to synchronize parts (tracking invites, ending the game, etc.). https://www.lucidchart.com/invitations/accept/72a85788-13ac-4443-956a-e2792aefc8fb

**Comment by gt-c** [comment]
Completed.

**Comment by cloewen8** [comment]
Not entirely. I still have features I have planned. Though I suppose I should create a new issue for them.
