### ISSUE TITLE
BroBit Dropping in-chat

### ISSUE THREAD

**Issue by ethanlaj** [Bro-Time/Bro-Time-Server#29]
Every 4-7 minutes, 1-3 BroBits will drop in the chat and users should be able to pick them up using !pick, or other commands (will be listed below). This system will only be put in #hangout.

# Functionality:
- Randomize # of minutes after a message is sent
15% - 4 minutes after a message is sent
25% - 5 minutes after a message is sent
35% - 6 minutes after a message is sent
25% - 7 minutes after a message is sent
-Randomize # of BroBits dropped
50% - 1 BroBit dropped
30% - 2 BroBits dropped
20% - 3 BroBits dropped
-If a timer is already running, a timer is not reset
-Once a BroBit is claimed, the embed is deleted (along with who claimed it)
-When a message is sent, a timer is set with a random time (times showed above). When the timer runs out, the bot will make sure at least two people are typing and if they are typing, it will put the BroBits out to claim. If two people are not typing at the same time, the bot waits until two people are typing and then posts the BroBits.

# How to prevent abuse of this system
- One user cannot claim BroBits 2x in a row. 
- Have many commands for this system. Each command has an equal chance of being picked to be used for this system.
!pick, !grab, !take, !steal, !mine, !snatch, !pull, !select, !choose, !get
- If a user is caught spamming any of these commands, the bot will ignore them for 7 days. 
- Admins and mods will be watching the chat

**Comment by gt-c** [comment]
DONE OK
