### ISSUE TITLE
BroBit Database Example

### ISSUE THREAD

**Issue by ethanlaj** [Bro-Time/Bro-Time-Server#358]
https://docs.google.com/spreadsheets/d/14aDUilCuBcloOXxSoQEmu8I4aKgh6bJJBzRps8_nLEg/edit?usp=sharing

**Comment by cloewen8** [comment]
Please use the ERD diagram provided. As an administrator, you should have the ability to directly edit it.

**Comment by gt-c** [comment]
Completed.
