### ISSUE TITLE
Music commands

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#396]
Music commands that take music off of YouTube and play them in a voice channel.

# Play

- [x] `!play (YouTube URL or context)` - Joins the voice channel the user is in (if not in a voice channel warns the user and doesn't do anything) and plays the YouTube URL supplied. If no URL it replies with 5 search results on YouTube videos that include the context. You can select the video desired by replying with 1 - 5, then it joins your voice channel (if in one) and plays the video. Adds the video to the queue. If all non-bot users leave the voice channel the bot stops playing music and leaves the channel in two minutes.

# Stop
- [x] `!stop` - Force stops the music and leaves the voice channel. If multiple non-bot users are in the channel, this starts a vote in which all non-bot users in the channel need to agree on by running the stop command as well. A moderator or person with the `DJ` role can force stop this without needing a vote.

# Queue
- [x] `!queue` - Displays a list of queued songs in a Rich Embed. Format: `1 - Name by Author (URL)` 

# Repeat
- [x] `!repeat [number]` - Starts a vote that if everyone in the voice channel agrees on, the queue is repeated infinitely. If the `number` parameter is supplied, it will repeat it the supplied amount times. If the `number` parameter is not a number it warns the user of this and does not do anything. A mod or person with the `DJ` role can force repeat the queue. If ran again (and the vote is agreed to), it toggles repeating the queue off.

# Volume
- [ ] `!volume (number, 1 - 100)` - Creates a vote in which everyone in the voice channel must agree on that allows the volume to be set to the specified amount. Default: 50. Mods or people with the `DJ` role can force set the volume (this is not a necessary command as it may be difficult to create). If the supplied parameter is not a number, or a number outside of the 1 - 100 range, the bot warns the user of this and doesn't do anything further.

## Note
By everyone in the voice channel, it implies everyone - 1 as the one person that played it will obviously object to what is desired by all the other users and that the user is not a bot user. If only one user is in the voice channel, it acts as if that user has the `DJ` role.

**Comment by ethanlaj** [comment]
play hypixel with me

**Comment by cloewen8** [comment]
Since both remove (skip) and clear (stop) option for the queue command already exists as separate commands. I will just add a queue command without options to view the queue.

**Comment by gt-c** [comment]
queue command clear is not needed, queue view is needed as well as queue remove

**Comment by gt-c** [comment]
skip may remove the value from the queue, but not until it starts playing, which isn’t much help trying to stop inappropriate music

**Comment by cloewen8** [comment]
The skip command could remove a song before it is played. It has access to the same data the queue command would have.
