### ISSUE TITLE
vote function addition - multiple id usage

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#400]
This feature would allow a user to run the vote function with the same id and not have it reject. This would work by toggling a vote on the vote with that id, as if the user added/removed the 👍 reaction. This would require adding a boolean value parameter to determine whether or not these feature is on (default: false). It would also require (if toggled) a parameter of the user that triggered the command.

**Comment by cloewen8** [comment]
If a user is provided as the last parameter, they will be added to the vote (existing or new). This will mean that the author no longer has to vote, on a vote they started (for user initiated votes).

**Comment by cloewen8** [comment]
`null` will be returned in the event that the vote is currently running.
