### ISSUE TITLE
DJs

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#403]
Users with a DJ role will be able to perform actions without needing to vote:

- [x] Stop playing music.
- [x] Remove from the queue.
- [x] Repeat the queue.
- [ ] Change the volume.

A user is implicitly a DJ if they are the only user playing music.

**Comment by gt-c** [comment]
New node module called dj which returns a true or false value on whether or not the member object supplied is a dj.
```js
const dj = require("app/dj");
dj(call.message.member) // If user has dj role or is a mod/admin, true, otherwise false.
```
