### ISSUE TITLE
#react-for-roles

### ISSUE THREAD

**Issue by ethanlaj** [Bro-Time/Bro-Time-Server#418]
In #react-for-roles, for each freerole, and for each game role, there will be a message. For each of those messages, bro bot will react with the :success: emoji (447207344426844187). When other users react with the success emoji, if they have the role designated to the message, it will be removed. If not, it will be added.

**Comment by cloewen8** [comment]
Would we need to scan, add, and remove roles every time the bot loads? Or should I just provide commands to add and remove roles?

**Comment by ethanlaj** [comment]
so onReact - adds role if doesn’t have 
                      - removes role if has
doesn’t scan people who reacted, as there should be none (except bro bot)

**Comment by gt-c** [comment]
Completed.
