### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#474]
Custom commands would be commands able to created by anyone, without knowledge on programming.
# How it would work
Custom commands would work by taking the users input and turning it into a buncha code and putting it in the database.
# Features
We will try to make custom commands as simple to make as possible, and stuff them full of features without actually allowing abuse.

Example:
`!custom create hello Hello!` would make the bot respond `Hello!` whenever a user ran the command `!hello`.

# Modifiers
These would be things you could put in your custom command to spice them up a bit.

Example:
`!custom create hello Hello {user}!` would make the bot respond `Hello @gt_c!` or whoever called the command.
`!custom create say {content}` would make the bot respond `xd lol!` whenever a user ran the command `!say xd lol!`

## A list of modifiers we should have:
Test case: A user named `@gt_c#0495` runs a custom command in the guild called `Bro Time` in the channel called `bot-usage`
### Guild modifiers
`{guild.name}` - Returns the guild name, in this case `Bro Time`
`{guild.id}` - Returns the guild id, in this case `330913265573953536`
`{guild.icon}` - Returns the guild logo, in this case `
https://cdn.discordapp.com/icons/330913265573953536/613c02fcdf7b9aed5f02e5689799188e.jpg`
`{guild.owner}` - Returns the mention of the guild owner, you can also use `{guild.owner.tag}` and everything else in the User modifiers section.
`{guild.creationdate}` - Returns the joindate of the owner, in this case `2017-07-02`
### User modifiers
`{user:username}` - Returns the user mention of the user supplied. You can also use other stuff in this such as `{user:username.discriminator}`.
`{user}` - Returns the mention of the user who ran the command, in this case `@gt_c#0495`
`{user.username}` - Returns the username of the user who ran the command, in this case `gt_c`
`{user.discriminator}` - Returns the discriminator of the user who ran the command, in this case `0495`
`{user.tag}` - Returns the tag of the user who ran the command, in this case `gt_c#0495`
`{user.joinDate}` - Returns the Discord join date of the user who ran the command in this case `2018-04-08`
`{user.joinedGuildDate}` - Returns the date when the user who ran the command joined the current guild, in this case `2018-05-14`
`{user.avatar}` - Returns the avatarURL of the user who ran the command, in this case `https://cdn.discordapp.com/avatars/432650511825633317/638a4ca480180c298c7bc6eea2478ae4.png?size=2048`
`{user.roles}` - Returns the first 10 roles the user has mapped by their names in a list seperated by commas. If none it returns an empty string. Example: `Co-Owner Bro, Blue, Developer Bro`
`{user.rolesCount}` - Returns the amount of roles the user has. In this case `3`
`{user.nickname}` - Returns the nickname of the user who ran the command. If the user has no nickname it returns the username of the user. In this case `gt_c`.
`{user.presence}` - Returns the presence of the user who ran the command. In this case `online`.
`{user.currentGame}` - Returns the current game name of the user who ran the command. If none it returns an empty string.
`{user.bot}` - Returns a boolean value (in a string) of whether or not the user is a bot account. In this case `false`
`{user.highestRole}` - Returns the name of the highest role the user has. You can also use `{user.highestRole.hexColor}` and everything else in the Role modifiers section.
### Role modifiers
`{role}` - Returns the name of the default role in the current guild. Always `@everyone`
`{role:rolename}` - Returns the name of the role specified. In this case `rolename`
`{role:rolename.id}` - Returns the role id of the role specified. In this case `1234567890`
`{role:rolename.color}` - Returns the role color in base 10 format of the role specified.
`{role:rolename.hexColor}` - Returns the role color in hex format of the role specified. If none, it returns `none`. In this case `#ff0000`.
`{role:rolename.mention}` - Returns the role mention of the role specified. This can't be abused as all roles are normally unmentionable.
`{role:rolename.madeAt}` - Returns the date the role specified was created at. In this case `2018-06-2`
`{role:rolename.mentionable}` - Returns whether or not the role specified is mentionable in boolean string format. In this case `false`
`{role:rolename.hoisted}` - Returns whether or not the role specified is hoisted in boolean string format. In this case `true`
`{role:rolename.members}` - Returns the first 10 members in the specified role seperated by commas and mapped by their tags. In this case `gt_c#0945, ethanlaj#8805`
`{role:rolename.memberCount}` - Returns the amount of members in the specified role in string format. In this case `2`.

**Comment by cloewen8** [comment]
I would like to see other language options added. To start, [Liquid](https://shopify.github.io/liquid/basics/introduction/).

**Comment by gt-c** [comment]
This may be added in the future, but currently this issue is so low priority that it’s better to just close it.

**Comment by cloewen8** [comment]
It's ok to leave issues open, even if it will take a while to implement. This is why we have milestones after all.
