### ISSUE TITLE
Why .catch(() => {}) should be allowed on message sending in d.js

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#488]
First of all there are a few set rules that can be easily avoided by the coder:
- Max length of message exceeds 2000 characters.
- Cannot send an empty message.
Then comes the API errors:
- DiscordAPIError: Missing Permissions, when the message cannot be sent due to lack of permission, whether the bot is not allowed to send messages, or if it cannot send embeds.

First we can eliminate the first two (`max-length` and `empty-message`) because the coder can easily avoid these if they want to. Now with the third one we can have it tell the user that it cannot speak in that channel if it runs into an error. If the user has dms off it simply ignores the error because it can't do anything to tell the user that it can't speak in that channel.

@cloewen8 You stated that what if there was a Discord API problem and we needed to see the error. First off, if there was a Discord API problem the bot would likely be down, and even if it wasn't, there would be no way of fixing it since it's Discord API not Bro Bot API.

Overall, message sending errors should not be logged as all it does is produces log spam.

**Comment by cloewen8** [comment]
The first rule is unrelated (you can't deploy it in the first place). That last rule can be accounted for if they check for permissions first (#465 for commands).

The default error handler is meant for exceptional situations. The last coarse of action is to log the error for administrators to take note of and potentially submit a bug report for (either for discord.js or our own server). There are some discord errors that we can account for (such as missing peer dependencies).

There are ways we can handle connection errors (send an email, stop handling events until ready, try another bot). If you have any suggestions, feel free to suggest them. We should never silently ignore all errors, especially from a framework that we do not control.

**Comment by ethanlaj** [comment]
I kinda agree with cj on this one, even though the way gtc is doing it, its hard to debug if all you're doing is silencing errors.

**Comment by gt-c** [comment]
I agree on that, you shouldn't use `.catch(() => {})` unless you have the code layed out. However that isn't relevant to the subject.

**Comment by ethanlaj** [comment]
Error messages need to be more specific, though. More information = better. Helps to solve the problem faster.
