### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#502]
TypeScript should be supported to add static type-checking. This change must be backwards compatible with the current source code. To accomplish this, TypeScript files should be acquirable using the same `require` function currently used. This could be accomplished by using [node-ts](https://github.com/TypeStrong/ts-node).

Using *node-ts* will require that all TypeScript modules are required with their extension (`.ts` or `.tsx`).

**Comment by cloewen8** [comment]
@ethanlaj, since you use Visual Studio Code, would you mind checking the Visual Studio Code section of node-ts and letting me know if I need to include anything for you?

**Comment by ethanlaj** [comment]
yo im not master at vs code whats node-ts

**Comment by ethanlaj** [comment]
wait a minute

**Comment by ethanlaj** [comment]
eslint uses nodejs and not node ts

**Comment by cloewen8** [comment]
It is possible to parse TypeScript into an ESlint assembly: https://github.com/eslint/typescript-eslint-parser
