### ISSUE TITLE
Server Data Communication

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#513]
If multiple shards are active, they may max out the Postgres connections pool. This interface should only be used by a single process. A module should be developed that sends and receives shard messages to perform common data tasks.

**Comment by gt-c** [comment]
I believe you could put this in the `server/launcher` file. And use `shard.send("POOL STUFF HERE")`  and handle it in the manager `message` event.

**Comment by cloewen8** [comment]
- [x] - Roundtrip test.
- [x] - GetPrefix method.
- [x] - SetPrefix method (untested).
- [ ] - Wallet access:
  - [ ] - WalletGetTotal method.
  - [ ] - WalletChange method.
  - [ ] - WalletTransfer method.
