### ISSUE TITLE
No database persistence, multiple logs.

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#515]
When the server is launched without a database connection the server obviously proceeds to disable database persistence. A warning is sent in the console like this:
`No database provided. The server will run without data persistence.`
Currently however this warning is sent multiple times. This is mildly annoying and should be fixed.

**Comment by cloewen8** [comment]
This is caused by the DataRequest code being run on both the parent and child processes. I'll split the code based on the context to fix this.
