### ISSUE TITLE
Remove Area Loading

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#516]
> No one uses them, with the addition of shards, they won't consistently run for every guild, and people don't seem to understand that they will always run for a guild or non-guild channel.

With the removal of the legacy data object, only a single area loader will remain (names.js; sets the nickname of the bot based on the current guild). This last area loader can easily be replaced with a regular loader. With the lack of benefits area loaders provide, they will be removed entirely.

**Comment by gt-c** [comment]
Appears to be done.
