### ISSUE TITLE
Automatic Command Cleanup

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#519]
After a command is called, the calling message and any interactions with it should automatically be cleaned up (prompts, user input, and time sensitive feedback).

This process should be carried out by the commands module. Each command should also have the option to register a message as part of the cleanup process.

This would eliminate the need for a commands channel and make them easier to use (as users don't have to be concerned with what channel they call a command in).

**Comment by cloewen8** [comment]
I plan to implement this into my own fan server bot if we need a test scenario.

**Comment by cloewen8** [comment]
I implemented this in my own bot by,

- classifying messages (input and output) as interactions,
- having commands register interactions,
- allowing commands to manually cleanup when finished,
- and by providing a finalize method to do cleanup automatically (if the command does not).

Unfortunately, Node.js does not have any way to access the garbage collector, so if this is implemented, all commands would need to manually trigger cleanup. If a command fails to do cleanup, the interactions will remain.

**Comment by gt-c** [comment]
If this is for deleting interactions with a command I **strongly** disagree with this idea. All this would do is cause confusion and chaos, ghost unread messages and pings (unread indicators or ping indicators with no new messages) and chat-log spam. This feature is essentially pointless. As for restricting commands to (a) specific channel(s) [guild preferences](
https://github.com/Bro-Time/Bro-Time-Server/issues/501) would cover that.

**Comment by cloewen8** [comment]
I still think this would be worth considering if Discord was to resolve the ghost pings issue (invalidate notifications when messages are deleted). Even if this feature was not added, users who have it configured would still get pinged and chat would still be added to the chat log.

If these 2 issues where to be resolved in the future, than would it be viable?

**Comment by cloewen8** [comment]
That is what I meant by the second issue. If Discord provided a method to disable pings for incoming messages, than it would not be a problem and would be worth implementing.

**Comment by gt-c** [comment]
By chat log I meant log for deleting messages. I am considering making a purge action sub command called 'commands' to delete previous command results and command triggers in the current channel. For now I am closing this issue. Feel free to create a new one about your requirements for this sub command if you want.
