### ISSUE TITLE
Vote Function Changes

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#532]
# Changes to vote function
The following change needs to be made to the voting function:
- [x] Adding a parameter to edit the message every x seconds instead of on reaction, this is to abide to api ratelimits and not have major vote lag (e.g updating to 50 when it’s at 60-70). 
- [x] This will be set on larger servers. [Note: Guild#large](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=large)
# Requirements to bypass vote for music commands.
- [x] Voting will require **at least** 75% of the **users** in the voice channel. As previous stated and accounted for in the isDj static method,
- [x] if a user is alone in voice channel, voting is not necessary.

**Comment by gt-c** [comment]
This isn't a full duplicate, please consider some of the ideas in this issue!

**Comment by cloewen8** [comment]
Please consider removing the duplicate information and organizing content into sections. It is a lot more encouraging when I can read an issue properly.

**Comment by gt-c** [comment]
Done.
