### ISSUE TITLE
Roblox Group Approval Process

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#539]
Currently, bot accounts can join the Bro Time Roblox group and post anything (Roblox lacks spam filtering). This allows for unwanted accounts to join the group and leave undesirable messages. To reduce the risk of these messages being left, a test should be designed for users to pass.

# Test
When a user joins, they will be required to pass a test in order to be approved. The test is simple, go to a Roblox game, and complete the main objective.

**Comment by gt-c** [comment]
The roblox utility module can accomplish most of the things you wish for here, including determining if a user is in the group, their rank in the group etc etc. However, it currently does not have any methods other than GET methods available, feel free to add those :D. (no i will not use roblox.js)

**Comment by cloewen8** [comment]
I'm also looking into having the group wall disabled entirely. We don't really need one since none of our traffic comes exclusively from Roblox (everyone uses Discord).

**Comment by cloewen8** [comment]
Posting to the group wall (for most members) has been disabled. This feature is now pointless.
