### ISSUE TITLE
Call.currency object

### ISSUE THREAD

**Issue by gt-c** [Bro-Time/Bro-Time-Server#540]
The Call.currency **object** not a class, is an object supplied as a property to the call class and to the game Session class, used to provide methods and values related to the currency (Bro Bits) some of the values will look like this:
getWallet: move from Call.getWallet to Call.currency.getWallet
Call.currency.getTotalMoney (name not decided): method that returns the total amount of Bro Bits out in 
BroBotlandia.
Call.currency.TRANSFER_RATE: The transfer rate of Wallet.transfer.
// more future currency-related features.

**Comment by cloewen8** [comment]
Why not provide the Wallet class? You can still access its methods in the exact same way as you would with an object, and it keeps the wallet code together.

**Comment by gt-c** [comment]
Implemented.
