### ISSUE TITLE
Music player is difficult to extend

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#542]
@gt-c noted that the music player was difficult to read and extend with commands. In order to resolve this, I need to know,

- [x] what parts are difficult to read,
- [x] what should be done to make it easier to read,
       Functions should perform a single task.
- [x] and what functionality needs to be exposed?
      A `call` may not always be available, Discord objects should be provided directly as much as possible. The music player should not interact with the user. Instead, events should be omitted to signal changes in its state.

A solution is needed that retains efficiency, and security.

**Comment by gt-c** [comment]
I have figured out a list of functions that I would prefer to be changed:
`displayQueued(call); --> `displayQueued(Guild);` - should return an array of the queue in that Guild.
`repeat(call, number);` --> `repeat(Guild, Number);` - should return a boolean whether or not the repeat was successful.
`toggle(call);` --> `toggle(Guild);` - should return a boolean on whether or not the toggling of the music in that guild was successful.
`skip(call);` --> `skip(Guild);` - should return a boolean on whether or not the current song was skipped.
`stop(call);` --> `stop(Guild);` - should return a boolean on whether the stop was successful.

Note that these may return promises if necassary, I didn't read enough of the file to know which ones do and which ones don't.

**Comment by cloewen8** [comment]
The music player is getting several events to handle state changes. The event will always include the guild id for the player. An optional channel id may also be included (to allow default event handlers to respond to users).
