### ISSUE TITLE
Improved addpartner command

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#550]
To better match with other commands,

- [x] `call.requestInput` should be used to gather customizations.

This would pave the way for further customizations to be added:

- [x] A different embed color - The partner's theme color or preference.
- [x] An image - Mascot or other partner representation.
- [x] Extra inline fields - Benefits or main points.

**Comment by ethanlaj** [comment]
call.requestInput, is that a thing?

**Comment by gt-c** [comment]
yes it is, and you rewrote a whole command with it :omegalul:
