### ISSUE TITLE
Mention command

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#551]
Mentioning Bro Bot (only) should execute the help command.

**Comment by gt-c** [comment]
Why? Are we removing greetings and the default prefix? I personally enjoy the fact that I can simply do `@Bro Bot prefix set abc` if someone such as ethan changes the prefix to something untypable. I disagree with this :P

**Comment by cloewen8** [comment]
This would not in any way impact the default prefix or greetings, since both of these features requires additional content in the message besides the mention. Currently, nothing happens if you only mention the bot.

**Comment by gt-c** [comment]
Misinterpreted this.

**Comment by gt-c** [comment]
I don't think we should do this, the help command returns a large embed in which should not be accidentally triggered.

**Comment by gt-c** [comment]
Finished
