### ISSUE TITLE
Obscure advertisements in names

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#553]
If a user's nickname contains an invite (using regex from [filter.js](https://github.com/Bro-Time/Bro-Time-Server/blob/7a14ffdf23cfd419ab7b27623d47dd75f190998e/server/chat/filter.js)), it should be replaced with a randomly generated name. If their status contains the invite, it will be reset to blank.

**Comment by cloewen8** [comment]
Possible regex? `discord\.[a-zA-Z]+[\/\\].+`
It does not account for workarounds (nor should it). I only intend for this feature to discourage users from trying to advertise in the server using nicknames.

**Comment by gt-c** [comment]
There is a regex in chat/filter that I use for discord invite matching, it should be exported so check it out.

**Comment by cloewen8** [comment]
A game could change their name periodically, spamming users with warnings. Especially if they are in multiple guilds with Bro Bot.

**Comment by cloewen8** [comment]
I won't do anything if the game is an advertisement in the mean time. If a plan can be devised which does not punish innocent members, I will implement it.
