### ISSUE TITLE
Nodemon uses wrong path

### ISSUE THREAD

**Issue by ethanlaj** [Bro-Time/Bro-Time-Server#558]
> PS C:\Repositories\Bro-Time-Server> nodemon
> [nodemon] 1.17.5
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: *.*
> [nodemon] starting `node server/server.js`
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\Repositories\Bro-Time-Server\server\server.js'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3

Needs support asap

**Comment by gt-c** [comment]
ur nodemon gay aka outdated

**Comment by ethanlaj** [comment]
rlly

**Comment by gt-c** [comment]
yeah its `node src/bot.ts` now

**Comment by ethanlaj** [comment]
how

**Comment by gt-c** [comment]
i dont know how you set it to `server/server.js`, but you need to change however you set it up. this is not a lack of bro bot supporting it, this is an issue you have to deal with yourself

**Comment by cloewen8** [comment]
Was this actually fixed? If not, this issue should stay open (it is still a bug, even if it is a bug in a yet-to-be-implemented feature).

**Comment by gt-c** [comment]
It was never an issue, so it could not be fixed by us, but by him.

**Comment by cloewen8** [comment]
I'll leave it open if it is something that needs fixing (even if only @ethanlaj can fix it).

**Comment by gt-c** [comment]
This.
Is.
Not.
A.
Problem.
With.
Bro.
Bot.
Ethan has already fixed this.
