### ISSUE TITLE
Pony command

### ISSUE THREAD

**Issue by cloewen8** [Bro-Time/Bro-Time-Server#570]
A command that attaches a random cute pony picture from Deviantart.

**Comment by ethanlaj** [comment]
yes

**Comment by ethanlaj** [comment]
this is top priority

**Comment by cloewen8** [comment]
I'm considering how to implement this. I don't think search is reliable enough so I may make a collection (there is an official api for this). I use DeviantArt enough to keep it fresh.

**Comment by cloewen8** [comment]
Made the folder: B9201D75-7B57-8D40-8014-D62EADB39280

I may need to cache results or only use the first page in the folder (newest first).

**Comment by thetechguy61705** [comment]
Yes this should be implemented As soon as possible

**Comment by gt-c** [comment]
Please remove the high priority label.

**Comment by cloewen8** [comment]
Does not change the effort I am putting into making it.
