### ISSUE TITLE
Publish Command

### ISSUE THREAD

**Issue by ethanlaj** [Bro-Time/Bro-Time-Server#9]
Right now everyone can ping the QOTD role and the game night role. This could make it easy to raid our server. To fix this, we could have a command that would turn on the permissions to ping the role when the command is used, then it would turn the permissions back off after. 

?publish qotd Favorite color?

**Comment by cloewen8** [comment]
How about if users could submit questions of the day to a queue instead? Than the bot could send the question to the channel?

**Comment by gt-c** [comment]
Completed
